machine:
  node:
    version: 8

dependencies:
  cache_directories:
    - "~/.cache/yarn"
    - node_modules

  override:
    - which node
    - yarn install

test:
  override:
    - node -v
    - yarn run test
