dist: trusty
language: node_js
install: true
node_js:
  - 7
  - 8

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV=TEST

before_install:
  - yarn versions
  - yarn upgrade

script:
  - yarn run test -- --coverage
