dist: trusty
language: node_js
install: true
node_js:
  - 7
  - 8

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV=TEST

before_install:
  - yarn install

script:
  - yarn run test -- --coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
