sudo: false

language: node_js
node_js:
  - "8"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn versions
  - yarn install
  - yarn upgrade

script:
  - true

after_success:
  - 'if [ $TRAVIS_BRANCH = "master" ]; then node ./bin/borderline-devutils.js publish; fi'
