version: 2

references:
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Environment verions
          command: yarn versions
      - run:
          name: Upgrading dependencies
          command: yarn upgrade
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Testing
          command: yarn run test -- --coverage
      - run:
          name: Exporting Coverage to CoverAlls
          command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
      - run:
          name: Exporting Coverage to CodeCov
          command: ./node_modules/codecov/bin/codecov
      - store_artifacts:
          path: ./coverage/lcov-report
          destination: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
      - test:
          context: org-global
          requires:
            - build
