version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:latest@sha256:029279af2fc78171cc7ee25c6a7f933a23213dd30ffd90e389afa4aee61d8ae3

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Environment verions
          command: yarn versions
      - run:
          name: Upgrading dependencies
          command: yarn upgrade
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

  propagate:
    <<: *defaults
    steps:
      - deploy:
          name: Trigger Consumers Build
          command: |
            curl -X POST "https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/borderline-ui/tree/master?circle-token=${CIRCLECI_TOKEN_BORDERLINE_UI}"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
    #  - propagate:
    #      context: org-global
