version: 2
jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: yarn run test -- --coverage

      # Coverage is being sent by TravisCI
      # - run:
      #     name: coverage
      #     command: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js --verbose
