version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:latest

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Environment verions
          command: yarn versions
      - run:
          name: Upgrading dependencies
          command: yarn upgrade
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - deploy:
          name: Publishing
          command: node ./bin/borderline-devutils.js publish
        # We are waiting for https://circleci.com/docs/api/v1-reference/ to implement workflow API
        # command: |
        #   node ./bin/borderline-devutils.js publish &&
        #   curl -X POST "https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/borderline-ui/tree/master?circle-token=${CIRCLECI_TOKEN_BORDERLINE_UI}"

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          context: org-global
      - publish:
          context: org-global
          requires:
            - build
